export const TOGGLE_MENU = 'TOGGLE_MENU'
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH'
export const SET_TRANSPOSE = 'SET_TRANSPOSE'

export const SEARCH_TEXT = 'SEARCH_TEXT'
export const FETCH_SEARCH_TEXT = 'FETCH_SEARCH_TEXT'
export const FETCH_SEARCH_TEXT_ERROR = 'FETCH_SEARCH_TEXT_ERROR'
export const FETCH_SEARCH_TEXT_SUCCESS = 'FETCH_SEARCH_TEXT_SUCCESS'
export const SEARCH_RESULT_CLICK = 'SEARCH_RESULT_CLICK'

export const SONGS = 'SONGS'
export const FETCH_SONGS = 'FETCH_SONGS'
export const FETCH_SONGS_ERROR = 'FETCH_SONGS_ERROR'
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS'

export const BROWSE = 'BROWSE'
export const BROWSE_SONGS = 'BROWSE_SONGS'
export const BROWSE_SONGS_ERROR = 'BROWSE_SONGS_ERROR'
export const BROWSE_SONGS_SUCCESS = 'BROWSE_SONGS_SUCCESS'

export const GET_CURRENT_SONG = 'GET_CURRENT_SONG'
export const FETCH_CURRENT_SONG_CHORDS = 'FETCH_CURRENT_SONG_CHORDS'
export const FETCH_CURRENT_SONG_CHORDS_ERROR = 'FETCH_CURRENT_SONG_CHORDS_ERROR'
export const FETCH_CURRENT_SONG_CHORDS_SUCCESS = 'FETCH_CURRENT_SONG_CHORDS_SUCCESS'

export const MOUNT_YT_PLAYER = 'MOUNT_YT_PLAYER'
export const UNMOUNT_YT_PLAYER = 'UNMOUNT_YT_PLAYER'
export const YT_PLAYER_STATUS_CHANGED = 'YT_PLAYER_STATUS_CHANGED'
export const MOVE_CHORD_TO = 'MOVE_CHORD_TO'