export const TOGGLE_MENU = 'TOGGLE_MENU'
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH'

export const SEARCH_TEXT = 'SEARCH_TEXT'
export const FETCH_SEARCH_TEXT = 'FETCH_SEARCH_TEXT'
export const FETCH_SEARCH_TEXT_ERROR = 'FETCH_SEARCH_TEXT_ERROR'
export const FETCH_SEARCH_TEXT_SUCCESS = 'FETCH_SEARCH_TEXT_SUCCESS'